# Generated by Django 2.2 on 2020-08-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzainfo',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
